name: "autodun"
version: "1.0"
config-version: 2
profile: "autodun_profile"
models:
  autodun:
    +materialized: table
    bronze:
      +schema: bronze
    silver:
      +schema: silver
    gold:
      +schema: gold
