name: Agent UI Fix

on:
  workflow_dispatch:
    inputs:
      goal:
        description: "Goal (UI-only)"
        required: false
        default: "Fix sticky Station Drawer; no Leaflet Popup; do NOT touch API or data"

permissions:
  contents: write

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Run agent (UI-only)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_PROJECT_ID: ${{ secrets.OPENAI_PROJECT_ID }}
          AGENT_GOAL: ${{ inputs.goal }}
        run: |
          npm run agent:fix

      - name: Tell user where to find the Vercel preview
        run: echo "Vercel builds a Preview automatically from the pushed branch. Check the Deployments tab for logs."
