name: e2e (playwright-chromium)
on:
  pull_request:
  push:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: npm ci
      # Ephemeral install so you don't have to edit package.json right now
      - run: npm i -D @playwright/test
      - run: npx playwright install --with-deps
      - env:
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE || 'http://localhost:3000' }}
        run: |
          npx next build
          npx next start -p 3000 &
          npx wait-on http://localhost:3000
          npx playwright test
