name: preview-build (vercel)
on:
  pull_request:

jobs:
  preview:
    runs-on: ubuntu-latest
    environment: preview
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: npm ci

      - name: Pull Vercel env
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN

      - name: Build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel build --token=$VERCEL_TOKEN

      - name: Deploy (prebuilt)
        id: deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          URL=$(npx vercel deploy --prebuilt --token=$VERCEL_TOKEN)
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Comment preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview-url
          message: "🔍 **Preview:** ${{ steps.deploy.outputs.url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
